[package]
name = "zirv-kafka"
version = "0.1.0"
edition = "2024"

[dependencies]
rdkafka = { version = "0.37.0", features = ["dynamic-linking"] }
serde_json = "1.0.140"
zirv-config = { version = "0.2.1" }